### ISSUE TITLE
Skelenox : exception when losing connectivity

### ISSUE THREAD

**Issue by 0x00ach** [ANSSI-FR/polichombr#151] opened 2017-10-09 12:31 UTC
Hi,

When the connectivity fails when viewing the "func Infos" tab, (i.e Error during request, retrying / Closing connection / Connecting using simple HTTP), skelenox still fails : poli_request,  res = self.h_conn.getresponse() triggers an httplib.BadStatusLine: '' exception.

Not sure why. Actually the sample is pretty big (>50k subs), and I've got an nginx setup, maybe related ?

Cheers,

**Comment by tpo-anssi** [comment] 2017-10-09 12:36
Hi,
It may be an nginx/uwsgi problem.

Could you provide the HTTP status code for the request ? (the endpoint should be `/api/1.0/samples/YOUR_SAMPLE_ID/functions/proposednames/` )

**Comment by 0x00ach** [comment] 2017-10-09 12:39
Everything's ok from a browser.

However, any further request from skelenox fail.

**Comment by tpo-anssi** [comment] 2017-10-09 12:43
So, that's sort out one possibility.

Could you provide an extract of _Skelenox_'s log and / or flask log?

Thanks

**Comment by 0x00ach** [comment] 2017-10-09 12:51
Flask : no error ;
Skelenox : 

[09/10/2017 02:18:48] [ERROR] [MainThread]: Error during request, retrying
[09/10/2017 02:18:48] [DEBUG] [MainThread]: Closing connection
[09/10/2017 02:18:48] [INFO] [MainThread]: Connecting using simple HTTP
...
  File "XXX/skelenox/skelenox.py", line 195, in poli_request
    res = self.h_conn.getresponse()
  File "C:\python27-x64\Lib\httplib.py", line 1121, in getresponse
...
httplib.BadStatusLine: ''

Remark : I cannot reproduce the error for now

**Comment by tpo-anssi** [comment] 2017-10-20 09:04
Hi 0x00,
If the issue is not reproducible, I am going to close it.

Feel free to reopen it should you have more connectivity problems!

Thanks,

**Closed by tpo-anssi** 2017-10-20 09:04 UTC
Labels: bug, skelenox
